# Path to your oh-my-zsh installation.
export ZSH=/home/adn/.oh-my-zsh
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="adn"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git mix-fast vi-mode)

# vi mode timeout
export KEYTIMEOUT=1

# User configuration
export EDITOR="vim"

# tmux italic support
# create the file xterm-256color-italic.terminfo with:
#
# xterm-256color-italic|xterm with 256 colors and italic,
#       sitm=\E[3m, ritm=\E[23m,
#               use=xterm-256color,
#
# tic xterm-256color-italic.terminfo
export TERM=xterm-256color-italic
alias ssh="TERM=xterm ssh"

export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin"

# export MANPATH="/usr/local/man:$MANPATH"

# add texlive to PATH
export PATH="/usr/local/texlive/2016/bin/x86_64-linux:$PATH"

# Elixir & Erlang
export ERL_AFLAGS="-kernel shell_history enabled"

# oh-my-zsh
source $ZSH/oh-my-zsh.sh

# asdf version manager for elm elixir erlang
# https://gist.github.com/rubencaro/6a28138a40e629b06470
source $HOME/.asdf/asdf.sh
source $HOME/.asdf/completions/asdf.bash

# Purescript version manager
export PATH="$HOME/.psvm/current/bin:$PATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# NVIM
# export NVIM_TUI_ENABLE_CURSOR_SHAPE=1

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

source "${HOME}/.sp.sh"

# Python virtualenvs
export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=$HOME/Devel
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source /usr/bin/virtualenvwrapper.sh

# yarn global
export PATH="$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# added by travis gem
[ -f /home/adn/.travis/travis.sh ] && source /home/adn/.travis/travis.sh

# --files: Print each file that would be searched without actually performing the search.
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Fix Delete Home and End on vi-mode
bindkey -a "^[[3~" delete-char
bindkey "^[[3~" delete-char
bindkey -a "^[[H" beginning-of-line
bindkey "^[[H" beginning-of-line
bindkey -a "^[[F" end-of-line
bindkey "^[[F" end-of-line
bindkey "^K" kill-line
# On tmux the keycodes change
bindkey -a "^[[1~" beginning-of-line
bindkey "^[[1~" beginning-of-line
bindkey -a "^[[4~" end-of-line
bindkey "^[[4~" end-of-line

# Beginning search with arrow keys
bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search
bindkey -a "^[OA" up-line-or-beginning-search

bindkey "^[b" backward-word
bindkey "^[[1;5D" backward-word
bindkey -a "^[[1;5D" backward-word
bindkey "^[f" forward-word
bindkey "^[[1;5C" forward-word
bindkey -a "^[[1;5C" forward-word

unalias grv
